### ISSUE TITLE
area scroll bars go to top when appending to area text with no word  to scroll it to bottom

### ISSUE THREAD

**Issue by GaryMiller** [red/docs#110]
Every time I append to the area that it scrolls the who way back up to the top even if I had i scrolled all the way down to the bottom. For things like logging and chat session and chat bots like I'm doing the information being added to the bottom is usually what the user is most interested in.

When I append text to an area, at some point the text is hidden from the user because it is scrolled off the screen. Is there a Red word I can use to tell the scroll bar on the area to scroll down so the user knows the new text has been appended. Otherwise I would have to inform the user to manually scroll to the bottom if he does not see a response in the area.

**Comment by 9214** [comment]
Is it a confirmed issue? If it is, then how is it related to documentation..?

**Comment by greggirwin** [comment]
This isn't a Doc issue. @GaryMiller, please raise the question on Gitter chat, if you haven't already.
