### ISSUE TITLE
Undocumented set-focus  for positioning cursor in a text box so the user doesn't need mouse click

### ISSUE THREAD

**Issue by GaryMiller** [red/docs#111]
amreus @amreus 08:57 found this for me on 12/29/2018

I found myself having to click on a text box each time I entered text because the control lost focus.

The set-focus worked beautifully but neither amreus or myself found it in the documentation.

amreus provided the following example and it worked like a charm!

Red [
    needs: 'view
]

view [
    f1: field focus
    f2: field
    f3: field
    b: button "Set Focus" [set-focus f3]
]

**Comment by greggirwin** [comment]
@gltewalt, could you add `set-focus` to https://doc.red-lang.org/en/view.html#_extra_functions ?

**Comment by gltewalt** [comment]
PR #112
