### ISSUE TITLE
Draw reference - Image

### ISSUE THREAD

**Issue by Rebol2Red** [red/docs#12]
https://dockimbel.gitbooks.io/red/content/v/v0.6.0/gui/Draw.html#image

I think this is wrong:

"If the image has positioning information provided,
then the image is painted at 0x0 coordinates."

Must be:

"If the image has positioning information provided,
then the image is painted at the given coordinates."

or

"If the image has no positioning information provided,
then the image is painted at 0x0 coordinates."

**Comment by geekyi** [comment]
I think this is a simple case of missing *no*; your 2nd example
