### ISSUE TITLE
bug at compile tine

### ISSUE THREAD

**Issue by tinulac-leinad** [red/docs#257]
in this code https://gist.github.com/tinulac-leinad/00a0e9a85e13782858eab2a71bc2ac59
there is a problem with I: here :
```
tune: object [
  tA: tB: tC: tD: tE: tF: tG: tH: I: tK: tL: tM: tN: tO: tP: tQ: tR: tS: tT: tX: tZ: ""
                                             
```
in the REPL the code work fine....
when I compile with -c it's ok
when I compile with -r -> error
```-=== Red Compiler 0.6.4 ===- 

Compiling /home/daniel/Apps/red/red_projets/dn-abc-tools/test.red ...
...compilation time : 1875 ms

Target: Linux 

Compiling to native code...
*** Compilation Error: argument type mismatch on calling: red/natives/repeat-init* 
*** expected: [struct! [
        header [integer!] 
        data1 [integer!] 
        data2 [integer!] 
        data3 [integer!]
    ]], found: [struct! [
        header [integer!] 
        ctx [pointer! [integer!]] 
        symbol [integer!] 
        index [integer!]
    ]] 
*** in file: %/home/daniel/Apps/red/red_projets/dn-abc-tools/test.red 
*** in function: exec/f_ctx||394~value-path?
*** at line: 1 
*** near: [
    r3: 0 
    stack/reset integer/push 0 
    stack/mark-loop ~repeat 
    while
]
```
and just this simple code cause the same error :
```
Red[]
I: none
```

**Comment by greggirwin** [comment]
`I: none` is all you need to trigger the compile error. Lowercase `i:`  doesn't cause it.

**Comment by hiiamboris** [comment]
https://github.com/red/red/issues/4526
close this one pls

**Comment by greggirwin** [comment]
It looks closed to me already @hiiamboris.

**Comment by greggirwin** [comment]
Ah, I see what you mean now. Wrong repo.

**Comment by tinulac-leinad** [comment]
> [red/red#4526](https://github.com/red/red/issues/4526)
> close this one pls

Oh, sorry this is not the good place to post this....

**Comment by hiiamboris** [comment]
> 
> 
> [red/red#4526](https://github.com/red/red/issues/4526)
> close this one pls

I should've linked https://github.com/red/red/issues/4770 , sorry, clipboard issues ;)
