### ISSUE TITLE
WISH: Make the asciidoc content format compatible with possible coming document translations

### ISSUE THREAD

**Issue by AT-Aoi** [red/docs#30]
I am working on Chinese translation of the documents. I find if only changing the text(no line added), the contents in github will be corrupted(like that original Japanese translation). After I add lines seperating elements(eg, header, code blocks), it will renders correctly. It seems seperated lines are need for some languages.

I can add lines needed while translating the documents. If permitted(needed), I will be happy to help.

**Comment by qtxie** [comment]
Yes. Of course you can.
