### ISSUE TITLE
Possible error in "Runtime creation" of Date documentation

### ISSUE THREAD

**Issue by Sh1noka** [red/docs#33]
There is possibily an error in the second note of the [Runtime creation](https://doc.red-lang.org/en/date.html#_runtime_creation). Maybe good to change to "only if its value is >= 100 and **greater** than the value of the third field". Also I think it is better to put it in the [Block to date](https://doc.red-lang.org/en/date.html#_block_to_date) section.

See [the discussion in gitter](https://gitter.im/red/help?at=5a76ac397dcd63481f15bbe4).

**Comment by gltewalt** [comment]
Is this closable now?

**Comment by greggirwin** [comment]
Yes, we went through this not long ago. Good catch.
