### ISSUE TITLE
The hierarchy in the English index is not anymore correct

### ISSUE THREAD

**Issue by meijeru** [red/docs#50]
Too many subsections under "datatypes"

**Comment by greggirwin** [comment]
@gltewalt is working on the %.adoc, which is problematic for links to sub pages. I just merged some updates.

**Comment by gltewalt** [comment]
Should be correct now.

**Comment by gltewalt** [comment]
Ok to close?

**Comment by greggirwin** [comment]
OK by me. @meijeru ?

**Comment by meijeru** [comment]
:+1:
