### ISSUE TITLE
Shape dialect's `arc` <angle> explanation is wrong

### ISSUE THREAD

**Issue by toomasv** [red/docs#69]
Documentation (https://doc.red-lang.org/en/draw.html#_arc_2) says:

`<angle>    : angle between the starting and ending points of the arc in degrees (integer! float!).`

Should be: `<angle>    : rotation angle of the underlying ellipse in degrees (integer! float!).`

Explanation: In following code angle between start and end points is 0 but rotation angle of ellipse is 45:
```
view [box 100x100 draw [shape [move 30x50 arc 70x50 30 20 45 large]]]
```

**Comment by gltewalt** [comment]
@greggirwin Is this ok to change?

**Comment by greggirwin** [comment]
If the correction makes it correct, it's the correct thing to do. So...yes.
