### ISSUE TITLE
Unnecessary example in error! doc

### ISSUE THREAD

**Issue by endo64** [red/docs#91]
It is not necessary to put below example in the end of section 3 (Creation) in error! datatype doc: page: https://doc.red-lang.org/en/datatypes/error.html#_creation

```
Arg values in the block are reduced.

>> cause-error 'syntax 'missing [foo bar]
*** Script Error: foo has no value
*** Where: reduce
*** Stack: cause-error
```

It is obvious that `foo` has no value and the error is not related to usage of `cause-error` function.

It can be removed or changed to 

```
Arg values in the block are reduced.

>> foo: "foo" bar: "bar"
>> cause-error 'syntax 'missing [foo bar]
*** Syntax Error: missing "foo" at "bar"
*** Where: reduce
*** Stack: cause-error
```

**Comment by gltewalt** [comment]
Ok to close @endo64

**Comment by endo64** [comment]
Thanks @gltewalt
